sudo: required
services:
  - docker

before_install:
  - docker build -t jamilshaikh07/docker-react -f Dockerfile.dev .

script:
  - docker run jamilshaikh07/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-606470338243"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_ACCESS_KEY_SECRET"