sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t jamilshaikh07/docker-react -f Dockerfile.dev .

scipt:
  - docker run jamilshaikh07/docker-react npm run test -- --coverage